language:
  - python

python:
  - "3.4"

before_install:
  - git submodule update --remote

install:
  - pip install six
  - pip install flake8
  - pip install jupyter
  - pip install -r requirements.txt

script:
  - py.test
  - python -m doctest -v *.py
  - flake8

notifications:
  email: false
